In [1]:
###-----------------
### Import Libraries
###-----------------

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

import warnings
warnings.filterwarnings('ignore')

In [2]:
boston=pd.read_csv("Boston.csv")

boston.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
X = boston.drop('medv',axis=1)
y = boston['medv']

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,
                                               test_size=0.3,
                                               random_state=23)

In [5]:
elastic=ElasticNet()
elastic.fit(X_train,y_train)

y_pred=elastic.predict(X_test)
print(r2_score(y_test,y_pred))

0.6588026707693808

# Grid_search cv

In [6]:
kfold=KFold(n_splits=5,shuffle=True,random_state=23)
elastic=ElasticNet()

l1_rat=np.linspace(0.001,0.999,20)
alphas=np.linspace(0.001,4,20)
params={'alpha':alphas,'l1_ratio':l1_rat}

gcv=GridSearchCV(elastic,param_grid=params,
                 cv=kfold,scoring='r2')
gcv.fit(X,y)

print(gcv.best_params_)
print(gcv.best_score_)

{'alpha': 0.001, 'l1_ratio': 0.7363684210526316}
0.7186439370747995

In [7]:
pd_cv=pd.DataFrame(gcv.cv_results_)    #Converted dictionary to DataFrame
pd_cv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006536,0.001401,0.003698,0.000777,0.001,0.001,"{'alpha': 0.001, 'l1_ratio': 0.001}",0.747827,0.689302,0.735261,0.680888,0.738284,0.718313,0.027566,20
1,0.003817,0.000207,0.002360,0.000198,0.001,0.053526,"{'alpha': 0.001, 'l1_ratio': 0.053526315789473...",0.747775,0.689479,0.735198,0.681011,0.738285,0.718349,0.027477,19
2,0.003506,0.000416,0.002488,0.000438,0.001,0.106053,"{'alpha': 0.001, 'l1_ratio': 0.10605263157894737}",0.747718,0.689658,0.735130,0.681136,0.738283,0.718385,0.027384,18
3,0.003505,0.000233,0.002237,0.000055,0.001,0.158579,"{'alpha': 0.001, 'l1_ratio': 0.15857894736842104}",0.747656,0.689841,0.735058,0.681262,0.738279,0.718419,0.027289,17
4,0.003274,0.000068,0.002170,0.000108,0.001,0.211105,"{'alpha': 0.001, 'l1_ratio': 0.21110526315789474}",0.747588,0.690028,0.734981,0.681391,0.738272,0.718452,0.027190,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.002865,0.000023,0.002095,0.000072,4.0,0.788895,"{'alpha': 4.0, 'l1_ratio': 0.7888947368421053}",0.545260,0.590815,0.585527,0.580164,0.563993,0.573152,0.016590,390
396,0.002808,0.000063,0.002062,0.000118,4.0,0.841421,"{'alpha': 4.0, 'l1_ratio': 0.841421052631579}",0.541345,0.585432,0.579573,0.576389,0.560187,0.568585,0.015987,394
397,0.002789,0.000024,0.002012,0.000074,4.0,0.893947,"{'alpha': 4.0, 'l1_ratio': 0.8939473684210526}",0.536843,0.579200,0.573041,0.572009,0.555674,0.563353,0.015373,397
398,0.002811,0.000124,0.002012,0.000075,4.0,0.946474,"{'alpha': 4.0, 'l1_ratio': 0.9464736842105264}",0.531604,0.571850,0.567716,0.566951,0.550549,0.557734,0.014955,399
399,0.002738,0.000018,0.001971,0.000039,4.0,0.999,"{'alpha': 4.0, 'l1_ratio': 0.999}",0.529995,0.567076,0.566763,0.562711,0.549836,0.555276,0.014108,400